version: "3"

services:
  mariadb:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=1234
      - MARIADB_DATABASE=registry
    ports:
      - 3307:3307
    volumes:
      - ./data/mariadb:/var/lib/mysql
